// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredCache = `-- name: CleanExpiredCache :execrows
DELETE FROM cache WHERE expires_at < NOW()
`

func (q *Queries) CleanExpiredCache(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanExpiredCache)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM cache WHERE key = $1
`

func (q *Queries) DeleteCache(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteCache, key)
	return err
}

const deleteCacheByPrefix = `-- name: DeleteCacheByPrefix :execrows
DELETE FROM cache WHERE key LIKE $1 || '%'
`

func (q *Queries) DeleteCacheByPrefix(ctx context.Context, dollar_1 *string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCacheByPrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCache = `-- name: GetCache :one
SELECT key, value, expires_at, created_at FROM cache
WHERE key = $1 AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetCache(ctx context.Context, key string) (Cache, error) {
	row := q.db.QueryRow(ctx, getCache, key)
	var i Cache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setCache = `-- name: SetCache :exec
INSERT INTO cache (key, value, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, expires_at = EXCLUDED.expires_at, created_at = NOW()
`

type SetCacheParams struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SetCache(ctx context.Context, arg SetCacheParams) error {
	_, err := q.db.Exec(ctx, setCache, arg.Key, arg.Value, arg.ExpiresAt)
	return err
}
