// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countSessionMessages = `-- name: CountSessionMessages :one
SELECT COUNT(*) FROM chat_messages WHERE session_id = $1
`

func (q *Queries) CountSessionMessages(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionMessages, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (session_id, role, content, tokens_used)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, role, content, tokens_used, created_at
`

type CreateChatMessageParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	Role       string    `json:"role"`
	Content    string    `json:"content"`
	TokensUsed *int32    `json:"tokens_used"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.TokensUsed,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (user_id, title, model, system_prompt)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, model, system_prompt, created_at, updated_at
`

type CreateChatSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Title        *string   `json:"title"`
	Model        *string   `json:"model"`
	SystemPrompt *string   `json:"system_prompt"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession,
		arg.UserID,
		arg.Title,
		arg.Model,
		arg.SystemPrompt,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Model,
		&i.SystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatMessage = `-- name: DeleteChatMessage :exec
DELETE FROM chat_messages WHERE id = $1
`

func (q *Queries) DeleteChatMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatMessage, id)
	return err
}

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE FROM chat_sessions WHERE id = $1 AND user_id = $2
`

type DeleteChatSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error {
	_, err := q.db.Exec(ctx, deleteChatSession, arg.ID, arg.UserID)
	return err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, session_id, role, content, tokens_used, created_at FROM chat_messages
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetChatMessages(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.TokensUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, title, model, system_prompt, created_at, updated_at FROM chat_sessions WHERE id = $1
`

func (q *Queries) GetChatSession(ctx context.Context, id uuid.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Model,
		&i.SystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatSessionByUser = `-- name: GetChatSessionByUser :one
SELECT id, user_id, title, model, system_prompt, created_at, updated_at FROM chat_sessions WHERE id = $1 AND user_id = $2
`

type GetChatSessionByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetChatSessionByUser(ctx context.Context, arg GetChatSessionByUserParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSessionByUser, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Model,
		&i.SystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentChatMessages = `-- name: GetRecentChatMessages :many
SELECT id, session_id, role, content, tokens_used, created_at FROM chat_messages
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentChatMessagesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetRecentChatMessages(ctx context.Context, arg GetRecentChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getRecentChatMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.TokensUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionTokenCount = `-- name: GetSessionTokenCount :one
SELECT COALESCE(SUM(tokens_used), 0)::INTEGER as total_tokens
FROM chat_messages WHERE session_id = $1
`

func (q *Queries) GetSessionTokenCount(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getSessionTokenCount, sessionID)
	var total_tokens int32
	err := row.Scan(&total_tokens)
	return total_tokens, err
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT id, user_id, title, model, system_prompt, created_at, updated_at FROM chat_sessions
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListChatSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Model,
			&i.SystemPrompt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatSession = `-- name: UpdateChatSession :one
UPDATE chat_sessions
SET title = COALESCE($2, title),
    system_prompt = COALESCE($3, system_prompt)
WHERE id = $1
RETURNING id, user_id, title, model, system_prompt, created_at, updated_at
`

type UpdateChatSessionParams struct {
	ID           uuid.UUID `json:"id"`
	Title        *string   `json:"title"`
	SystemPrompt *string   `json:"system_prompt"`
}

func (q *Queries) UpdateChatSession(ctx context.Context, arg UpdateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, updateChatSession, arg.ID, arg.Title, arg.SystemPrompt)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Model,
		&i.SystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
