// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cache struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatMessage struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	TokensUsed *int32             `json:"tokens_used"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Title        *string            `json:"title"`
	Model        *string            `json:"model"`
	SystemPrompt *string            `json:"system_prompt"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	Revoked   *bool              `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  *string            `json:"password_hash"`
	Name          string             `json:"name"`
	AvatarUrl     *string            `json:"avatar_url"`
	Provider      *string            `json:"provider"`
	ProviderID    *string            `json:"provider_id"`
	EmailVerified *bool              `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
