// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cache struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatMessage struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	TokensUsed *int32             `json:"tokens_used"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Title        *string            `json:"title"`
	Model        *string            `json:"model"`
	SystemPrompt *string            `json:"system_prompt"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	Revoked   *bool              `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  *string            `json:"password_hash"`
	Name          string             `json:"name"`
	AvatarUrl     *string            `json:"avatar_url"`
	Provider      *string            `json:"provider"`
	ProviderID    *string            `json:"provider_id"`
	EmailVerified *bool              `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BusinessUnderstanding struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	UserName           *string            `json:"user_name"`
	JobTitle           *string            `json:"job_title"`
	BusinessName       *string            `json:"business_name"`
	Industry           *string            `json:"industry"`
	BusinessSize       *string            `json:"business_size"`
	UserRole           *string            `json:"user_role"`
	KeyWorkflows       []byte             `json:"key_workflows"`
	DailyActivities    []byte             `json:"daily_activities"`
	PainPoints         []byte             `json:"pain_points"`
	Bottlenecks        []byte             `json:"bottlenecks"`
	ManualTasks        []byte             `json:"manual_tasks"`
	AutomationGoals    []byte             `json:"automation_goals"`
	CurrentSoftware    []byte             `json:"current_software"`
	ExistingAutomation []byte             `json:"existing_automation"`
	AdditionalNotes    *string            `json:"additional_notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Referral tracking models

type ReferralCode struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Code             string             `json:"code"`
	Industry         *string            `json:"industry"`
	BusinessSize     *string            `json:"business_size"`
	TotalShares      int32              `json:"total_shares"`
	TotalClicks      int32              `json:"total_clicks"`
	TotalSignups     int32              `json:"total_signups"`
	TotalActivations int32              `json:"total_activations"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ReferralShare struct {
	ID             uuid.UUID          `json:"id"`
	ReferrerID     uuid.UUID          `json:"referrer_id"`
	ReferralCodeID uuid.UUID          `json:"referral_code_id"`
	ShareChannel   string             `json:"share_channel"`
	ShareSource    *string            `json:"share_source"`
	Completed      *bool              `json:"completed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReferralClick struct {
	ID              uuid.UUID          `json:"id"`
	ReferralCodeID  uuid.UUID          `json:"referral_code_id"`
	VisitorID       *string            `json:"visitor_id"`
	IpHash          *string            `json:"ip_hash"`
	UserAgent       *string            `json:"user_agent"`
	LandingPage     *string            `json:"landing_page"`
	UtmSource       *string            `json:"utm_source"`
	UtmMedium       *string            `json:"utm_medium"`
	UtmCampaign     *string            `json:"utm_campaign"`
	ConvertedUserID *uuid.UUID         `json:"converted_user_id"`
	ConvertedAt     pgtype.Timestamptz `json:"converted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReferralSignup struct {
	ID                    uuid.UUID          `json:"id"`
	RefereeID             uuid.UUID          `json:"referee_id"`
	ReferrerID            uuid.UUID          `json:"referrer_id"`
	ReferralCodeID        uuid.UUID          `json:"referral_code_id"`
	ClickID               *uuid.UUID         `json:"click_id"`
	InheritedIndustry     *string            `json:"inherited_industry"`
	InheritedBusinessSize *string            `json:"inherited_business_size"`
	ActivatedAt           pgtype.Timestamptz `json:"activated_at"`
	FirstReportAt         pgtype.Timestamptz `json:"first_report_at"`
	Status                *string            `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
