// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanExpiredCache(ctx context.Context) (int64, error)
	CleanExpiredTokens(ctx context.Context) (int64, error)
	CountSessionMessages(ctx context.Context, sessionID uuid.UUID) (int64, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBusinessUnderstanding(ctx context.Context, userID uuid.UUID) error
	DeleteCache(ctx context.Context, key string) error
	DeleteCacheByPrefix(ctx context.Context, dollar_1 *string) (int64, error)
	DeleteChatMessage(ctx context.Context, id uuid.UUID) error
	DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetBusinessUnderstanding(ctx context.Context, userID uuid.UUID) (BusinessUnderstanding, error)
	GetCache(ctx context.Context, key string) (Cache, error)
	GetChatMessages(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error)
	GetChatSession(ctx context.Context, id uuid.UUID) (ChatSession, error)
	GetChatSessionByUser(ctx context.Context, arg GetChatSessionByUserParams) (ChatSession, error)
	GetRecentChatMessages(ctx context.Context, arg GetRecentChatMessagesParams) ([]ChatMessage, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSessionTokenCount(ctx context.Context, sessionID uuid.UUID) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error)
	ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]ChatSession, error)
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetCache(ctx context.Context, arg SetCacheParams) error
	UpdateChatSession(ctx context.Context, arg UpdateChatSessionParams) (ChatSession, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertBusinessUnderstanding(ctx context.Context, arg UpsertBusinessUnderstandingParams) (BusinessUnderstanding, error)
	// Referral tracking methods
	CountReferralSharesByReferrer(ctx context.Context, referrerID uuid.UUID) (int64, error)
	CountReferralSignupsByReferrer(ctx context.Context, referrerID uuid.UUID) (int64, error)
	CreateReferralClick(ctx context.Context, arg CreateReferralClickParams) (ReferralClick, error)
	CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (ReferralCode, error)
	CreateReferralShare(ctx context.Context, arg CreateReferralShareParams) (ReferralShare, error)
	CreateReferralSignup(ctx context.Context, arg CreateReferralSignupParams) (ReferralSignup, error)
	GetReferralCodeByCode(ctx context.Context, code string) (ReferralCode, error)
	GetReferralCodeByUserID(ctx context.Context, userID uuid.UUID) (ReferralCode, error)
	GetReferralClickByVisitor(ctx context.Context, visitorID *string) (ReferralClick, error)
	GetReferralLeaderboard(ctx context.Context, limit int32) ([]GetReferralLeaderboardRow, error)
	GetReferralSharesByReferrer(ctx context.Context, referrerID uuid.UUID, limit int32) ([]ReferralShare, error)
	GetReferralSignupByReferee(ctx context.Context, refereeID uuid.UUID) (ReferralSignup, error)
	GetReferralSignupsByReferrer(ctx context.Context, referrerID uuid.UUID, limit int32, offset int32) ([]GetReferralSignupsByReferrerRow, error)
	GetReferralStats(ctx context.Context, userID uuid.UUID) (GetReferralStatsRow, error)
	IncrementReferralActivations(ctx context.Context, id uuid.UUID) error
	IncrementReferralClicks(ctx context.Context, id uuid.UUID) error
	IncrementReferralShares(ctx context.Context, id uuid.UUID) error
	IncrementReferralSignups(ctx context.Context, id uuid.UUID) error
	UpdateReferralClickConverted(ctx context.Context, arg UpdateReferralClickConvertedParams) error
	UpdateReferralSignupActivated(ctx context.Context, refereeID uuid.UUID) error
	UpdateReferralSignupFirstReport(ctx context.Context, refereeID uuid.UUID) error
	UpdateReferralSignupStatus(ctx context.Context, arg UpdateReferralSignupStatusParams) error
}

var _ Querier = (*Queries)(nil)
