// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referrals.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

// Referral Codes

const createReferralCode = `-- name: CreateReferralCode :one
INSERT INTO referral_codes (user_id, code, industry, business_size)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code, industry, business_size, total_shares, total_clicks, total_signups, total_activations, created_at, updated_at
`

type CreateReferralCodeParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Code         string    `json:"code"`
	Industry     *string   `json:"industry"`
	BusinessSize *string   `json:"business_size"`
}

func (q *Queries) CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, createReferralCode,
		arg.UserID,
		arg.Code,
		arg.Industry,
		arg.BusinessSize,
	)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Industry,
		&i.BusinessSize,
		&i.TotalShares,
		&i.TotalClicks,
		&i.TotalSignups,
		&i.TotalActivations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralCodeByUserID = `-- name: GetReferralCodeByUserID :one
SELECT id, user_id, code, industry, business_size, total_shares, total_clicks, total_signups, total_activations, created_at, updated_at FROM referral_codes WHERE user_id = $1
`

func (q *Queries) GetReferralCodeByUserID(ctx context.Context, userID uuid.UUID) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeByUserID, userID)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Industry,
		&i.BusinessSize,
		&i.TotalShares,
		&i.TotalClicks,
		&i.TotalSignups,
		&i.TotalActivations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralCodeByCode = `-- name: GetReferralCodeByCode :one
SELECT id, user_id, code, industry, business_size, total_shares, total_clicks, total_signups, total_activations, created_at, updated_at FROM referral_codes WHERE code = $1
`

func (q *Queries) GetReferralCodeByCode(ctx context.Context, code string) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeByCode, code)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Industry,
		&i.BusinessSize,
		&i.TotalShares,
		&i.TotalClicks,
		&i.TotalSignups,
		&i.TotalActivations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementReferralShares = `-- name: IncrementReferralShares :exec
UPDATE referral_codes SET total_shares = total_shares + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementReferralShares(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReferralShares, id)
	return err
}

const incrementReferralClicks = `-- name: IncrementReferralClicks :exec
UPDATE referral_codes SET total_clicks = total_clicks + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementReferralClicks(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReferralClicks, id)
	return err
}

const incrementReferralSignups = `-- name: IncrementReferralSignups :exec
UPDATE referral_codes SET total_signups = total_signups + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementReferralSignups(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReferralSignups, id)
	return err
}

const incrementReferralActivations = `-- name: IncrementReferralActivations :exec
UPDATE referral_codes SET total_activations = total_activations + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementReferralActivations(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReferralActivations, id)
	return err
}

// Referral Shares

const createReferralShare = `-- name: CreateReferralShare :one
INSERT INTO referral_shares (referrer_id, referral_code_id, share_channel, share_source, completed)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, referrer_id, referral_code_id, share_channel, share_source, completed, created_at
`

type CreateReferralShareParams struct {
	ReferrerID     uuid.UUID `json:"referrer_id"`
	ReferralCodeID uuid.UUID `json:"referral_code_id"`
	ShareChannel   string    `json:"share_channel"`
	ShareSource    *string   `json:"share_source"`
	Completed      *bool     `json:"completed"`
}

func (q *Queries) CreateReferralShare(ctx context.Context, arg CreateReferralShareParams) (ReferralShare, error) {
	row := q.db.QueryRow(ctx, createReferralShare,
		arg.ReferrerID,
		arg.ReferralCodeID,
		arg.ShareChannel,
		arg.ShareSource,
		arg.Completed,
	)
	var i ReferralShare
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.ReferralCodeID,
		&i.ShareChannel,
		&i.ShareSource,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralSharesByReferrer = `-- name: GetReferralSharesByReferrer :many
SELECT id, referrer_id, referral_code_id, share_channel, share_source, completed, created_at FROM referral_shares WHERE referrer_id = $1 ORDER BY created_at DESC LIMIT $2
`

func (q *Queries) GetReferralSharesByReferrer(ctx context.Context, referrerID uuid.UUID, limit int32) ([]ReferralShare, error) {
	rows, err := q.db.Query(ctx, getReferralSharesByReferrer, referrerID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferralShare{}
	for rows.Next() {
		var i ReferralShare
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.ReferralCodeID,
			&i.ShareChannel,
			&i.ShareSource,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReferralSharesByReferrer = `-- name: CountReferralSharesByReferrer :one
SELECT COUNT(*) FROM referral_shares WHERE referrer_id = $1
`

func (q *Queries) CountReferralSharesByReferrer(ctx context.Context, referrerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralSharesByReferrer, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// Referral Clicks

const createReferralClick = `-- name: CreateReferralClick :one
INSERT INTO referral_clicks (
    referral_code_id, visitor_id, ip_hash, user_agent,
    landing_page, utm_source, utm_medium, utm_campaign
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, referral_code_id, visitor_id, ip_hash, user_agent, landing_page, utm_source, utm_medium, utm_campaign, converted_user_id, converted_at, created_at
`

type CreateReferralClickParams struct {
	ReferralCodeID uuid.UUID `json:"referral_code_id"`
	VisitorID      *string   `json:"visitor_id"`
	IpHash         *string   `json:"ip_hash"`
	UserAgent      *string   `json:"user_agent"`
	LandingPage    *string   `json:"landing_page"`
	UtmSource      *string   `json:"utm_source"`
	UtmMedium      *string   `json:"utm_medium"`
	UtmCampaign    *string   `json:"utm_campaign"`
}

func (q *Queries) CreateReferralClick(ctx context.Context, arg CreateReferralClickParams) (ReferralClick, error) {
	row := q.db.QueryRow(ctx, createReferralClick,
		arg.ReferralCodeID,
		arg.VisitorID,
		arg.IpHash,
		arg.UserAgent,
		arg.LandingPage,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
	)
	var i ReferralClick
	err := row.Scan(
		&i.ID,
		&i.ReferralCodeID,
		&i.VisitorID,
		&i.IpHash,
		&i.UserAgent,
		&i.LandingPage,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.ConvertedUserID,
		&i.ConvertedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralClickByVisitor = `-- name: GetReferralClickByVisitor :one
SELECT id, referral_code_id, visitor_id, ip_hash, user_agent, landing_page, utm_source, utm_medium, utm_campaign, converted_user_id, converted_at, created_at FROM referral_clicks
WHERE visitor_id = $1 AND converted_user_id IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetReferralClickByVisitor(ctx context.Context, visitorID *string) (ReferralClick, error) {
	row := q.db.QueryRow(ctx, getReferralClickByVisitor, visitorID)
	var i ReferralClick
	err := row.Scan(
		&i.ID,
		&i.ReferralCodeID,
		&i.VisitorID,
		&i.IpHash,
		&i.UserAgent,
		&i.LandingPage,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.ConvertedUserID,
		&i.ConvertedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateReferralClickConverted = `-- name: UpdateReferralClickConverted :exec
UPDATE referral_clicks
SET converted_user_id = $2, converted_at = NOW()
WHERE id = $1
`

type UpdateReferralClickConvertedParams struct {
	ID              uuid.UUID `json:"id"`
	ConvertedUserID uuid.UUID `json:"converted_user_id"`
}

func (q *Queries) UpdateReferralClickConverted(ctx context.Context, arg UpdateReferralClickConvertedParams) error {
	_, err := q.db.Exec(ctx, updateReferralClickConverted, arg.ID, arg.ConvertedUserID)
	return err
}

// Referral Signups

const createReferralSignup = `-- name: CreateReferralSignup :one
INSERT INTO referral_signups (
    referee_id, referrer_id, referral_code_id, click_id,
    inherited_industry, inherited_business_size, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, referee_id, referrer_id, referral_code_id, click_id, inherited_industry, inherited_business_size, activated_at, first_report_at, status, created_at, updated_at
`

type CreateReferralSignupParams struct {
	RefereeID             uuid.UUID  `json:"referee_id"`
	ReferrerID            uuid.UUID  `json:"referrer_id"`
	ReferralCodeID        uuid.UUID  `json:"referral_code_id"`
	ClickID               *uuid.UUID `json:"click_id"`
	InheritedIndustry     *string    `json:"inherited_industry"`
	InheritedBusinessSize *string    `json:"inherited_business_size"`
	Status                *string    `json:"status"`
}

func (q *Queries) CreateReferralSignup(ctx context.Context, arg CreateReferralSignupParams) (ReferralSignup, error) {
	row := q.db.QueryRow(ctx, createReferralSignup,
		arg.RefereeID,
		arg.ReferrerID,
		arg.ReferralCodeID,
		arg.ClickID,
		arg.InheritedIndustry,
		arg.InheritedBusinessSize,
		arg.Status,
	)
	var i ReferralSignup
	err := row.Scan(
		&i.ID,
		&i.RefereeID,
		&i.ReferrerID,
		&i.ReferralCodeID,
		&i.ClickID,
		&i.InheritedIndustry,
		&i.InheritedBusinessSize,
		&i.ActivatedAt,
		&i.FirstReportAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralSignupByReferee = `-- name: GetReferralSignupByReferee :one
SELECT id, referee_id, referrer_id, referral_code_id, click_id, inherited_industry, inherited_business_size, activated_at, first_report_at, status, created_at, updated_at FROM referral_signups WHERE referee_id = $1
`

func (q *Queries) GetReferralSignupByReferee(ctx context.Context, refereeID uuid.UUID) (ReferralSignup, error) {
	row := q.db.QueryRow(ctx, getReferralSignupByReferee, refereeID)
	var i ReferralSignup
	err := row.Scan(
		&i.ID,
		&i.RefereeID,
		&i.ReferrerID,
		&i.ReferralCodeID,
		&i.ClickID,
		&i.InheritedIndustry,
		&i.InheritedBusinessSize,
		&i.ActivatedAt,
		&i.FirstReportAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralSignupsByReferrer = `-- name: GetReferralSignupsByReferrer :many
SELECT rs.id, rs.referee_id, rs.referrer_id, rs.referral_code_id, rs.click_id, rs.inherited_industry, rs.inherited_business_size, rs.activated_at, rs.first_report_at, rs.status, rs.created_at, rs.updated_at, u.email as referee_email, u.name as referee_name
FROM referral_signups rs
JOIN users u ON rs.referee_id = u.id
WHERE rs.referrer_id = $1
ORDER BY rs.created_at DESC
LIMIT $2 OFFSET $3
`

type GetReferralSignupsByReferrerRow struct {
	ReferralSignup
	RefereeEmail string `json:"referee_email"`
	RefereeName  string `json:"referee_name"`
}

func (q *Queries) GetReferralSignupsByReferrer(ctx context.Context, referrerID uuid.UUID, limit int32, offset int32) ([]GetReferralSignupsByReferrerRow, error) {
	rows, err := q.db.Query(ctx, getReferralSignupsByReferrer, referrerID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReferralSignupsByReferrerRow{}
	for rows.Next() {
		var i GetReferralSignupsByReferrerRow
		if err := rows.Scan(
			&i.ID,
			&i.RefereeID,
			&i.ReferrerID,
			&i.ReferralCodeID,
			&i.ClickID,
			&i.InheritedIndustry,
			&i.InheritedBusinessSize,
			&i.ActivatedAt,
			&i.FirstReportAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefereeEmail,
			&i.RefereeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReferralSignupsByReferrer = `-- name: CountReferralSignupsByReferrer :one
SELECT COUNT(*) FROM referral_signups WHERE referrer_id = $1
`

func (q *Queries) CountReferralSignupsByReferrer(ctx context.Context, referrerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralSignupsByReferrer, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateReferralSignupActivated = `-- name: UpdateReferralSignupActivated :exec
UPDATE referral_signups
SET activated_at = NOW(), status = 'activated', updated_at = NOW()
WHERE referee_id = $1
`

func (q *Queries) UpdateReferralSignupActivated(ctx context.Context, refereeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateReferralSignupActivated, refereeID)
	return err
}

const updateReferralSignupFirstReport = `-- name: UpdateReferralSignupFirstReport :exec
UPDATE referral_signups
SET first_report_at = NOW(), status = 'generated_report', updated_at = NOW()
WHERE referee_id = $1
`

func (q *Queries) UpdateReferralSignupFirstReport(ctx context.Context, refereeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateReferralSignupFirstReport, refereeID)
	return err
}

const updateReferralSignupStatus = `-- name: UpdateReferralSignupStatus :exec
UPDATE referral_signups
SET status = $2, updated_at = NOW()
WHERE referee_id = $1
`

type UpdateReferralSignupStatusParams struct {
	RefereeID uuid.UUID `json:"referee_id"`
	Status    *string   `json:"status"`
}

func (q *Queries) UpdateReferralSignupStatus(ctx context.Context, arg UpdateReferralSignupStatusParams) error {
	_, err := q.db.Exec(ctx, updateReferralSignupStatus, arg.RefereeID, arg.Status)
	return err
}

// Analytics Queries

const getReferralStats = `-- name: GetReferralStats :one
SELECT
    rc.id,
    rc.code,
    rc.total_shares,
    rc.total_clicks,
    rc.total_signups,
    rc.total_activations,
    CASE WHEN rc.total_clicks > 0
         THEN (rc.total_signups::float / rc.total_clicks::float * 100)::numeric(5,2)
         ELSE 0 END as click_to_signup_rate,
    CASE WHEN rc.total_signups > 0
         THEN (rc.total_activations::float / rc.total_signups::float * 100)::numeric(5,2)
         ELSE 0 END as activation_rate
FROM referral_codes rc
WHERE rc.user_id = $1
`

type GetReferralStatsRow struct {
	ID                  uuid.UUID `json:"id"`
	Code                string    `json:"code"`
	TotalShares         int32     `json:"total_shares"`
	TotalClicks         int32     `json:"total_clicks"`
	TotalSignups        int32     `json:"total_signups"`
	TotalActivations    int32     `json:"total_activations"`
	ClickToSignupRate   float64   `json:"click_to_signup_rate"`
	ActivationRate      float64   `json:"activation_rate"`
}

func (q *Queries) GetReferralStats(ctx context.Context, userID uuid.UUID) (GetReferralStatsRow, error) {
	row := q.db.QueryRow(ctx, getReferralStats, userID)
	var i GetReferralStatsRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TotalShares,
		&i.TotalClicks,
		&i.TotalSignups,
		&i.TotalActivations,
		&i.ClickToSignupRate,
		&i.ActivationRate,
	)
	return i, err
}

const getReferralLeaderboard = `-- name: GetReferralLeaderboard :many
SELECT
    u.id as user_id,
    u.name,
    rc.code,
    rc.total_signups,
    rc.total_activations
FROM referral_codes rc
JOIN users u ON rc.user_id = u.id
WHERE rc.total_signups > 0
ORDER BY rc.total_activations DESC, rc.total_signups DESC
LIMIT $1
`

type GetReferralLeaderboardRow struct {
	UserID           uuid.UUID `json:"user_id"`
	Name             string    `json:"name"`
	Code             string    `json:"code"`
	TotalSignups     int32     `json:"total_signups"`
	TotalActivations int32     `json:"total_activations"`
}

func (q *Queries) GetReferralLeaderboard(ctx context.Context, limit int32) ([]GetReferralLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getReferralLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReferralLeaderboardRow{}
	for rows.Next() {
		var i GetReferralLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Code,
			&i.TotalSignups,
			&i.TotalActivations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
