# Alternative CI Workflow - Parallel Separate Jobs
#
# This is Option 2 from CI_OPTIMIZATION.md:
# Keep 3 separate jobs but remove sequential dependencies.
# Expected time: 20-30 seconds
#
# Benefits:
# - Clearer error reporting (each job shows its own status)
# - Easier to understand GitHub Actions UI
# - Still fast due to parallel execution
#
# Use this if you prefer the cleaner job separation over
# the slightly faster single-job approach in ci.yml

name: CI (Parallel Jobs)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Cancel in-progress runs for the same branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # NOTE: No 'needs' dependency - runs in parallel with lint and test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # NOTE: No 'needs' dependency - runs in parallel with lint and build
    # NOTE: No PostgreSQL service - unit tests don't need database
    # NOTE: No -race flag - race detection moved to nightly workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run unit tests
        run: go test -v -timeout 30s -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./coverage.out
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
